package com.abili.model;
// Generated 2016-9-3 12:31:46 by Hibernate Tools 3.4.0.CR1

/**
 * Info generated by hbm2java
 */
public class Info implements java.io.Serializable {

	private Integer infoid;
	private String intro;
	private Integer minage;
	private Integer maxage;
	private Integer buyer;
	private String name;
	private String type;
	private Double price;
	private Integer time;

	public Info() {
	}

	public Info(String intro, Integer minage, Integer maxage, Integer buyer, String name, String type, Double price,
			Integer time) {
		this.intro = intro;
		this.minage = minage;
		this.maxage = maxage;
		this.buyer = buyer;
		this.name = name;
		this.type = type;
		this.price = price;
		this.time = time;
	}

	public Integer getInfoid() {
		return this.infoid;
	}

	public void setInfoid(Integer infoid) {
		this.infoid = infoid;
	}

	public String getIntro() {
		return this.intro;
	}

	public void setIntro(String intro) {
		this.intro = intro;
	}

	public Integer getMinage() {
		return this.minage;
	}

	public void setMinage(Integer minage) {
		this.minage = minage;
	}

	public Integer getMaxage() {
		return this.maxage;
	}

	public void setMaxage(Integer maxage) {
		this.maxage = maxage;
	}

	public Integer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Integer buyer) {
		this.buyer = buyer;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getTime() {
		return this.time;
	}

	public void setTime(Integer time) {
		this.time = time;
	}

}
