package com.abili.model;
// Generated 2016-9-3 12:31:46 by Hibernate Tools 3.4.0.CR1

/**
 * Work generated by hbm2java
 */
public class Work implements java.io.Serializable {

	private Integer workerid;
	private String username;
	private String password;
	private String name;

	public Work() {
	}

	public Work(String username, String password, String name) {
		this.username = username;
		this.password = password;
		this.name = name;
	}

	public Integer getWorkerid() {
		return this.workerid;
	}

	public void setWorkerid(Integer workerid) {
		this.workerid = workerid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
